### ISSUE TITLE
VXRD: Uploads

### ISSUE THREAD

**Issue by sabaronett** [qzhu2017/XRD#20]
## Issues
- ~Currently, after a successful submission, form requires user to re-upload CIF.~
- Since POSCAR doesn't have file ext., had to temp. disabled built-in file upload form validator
   - Bad files (CIF/POSCAR) or other file formats result in error

## Tasks
- [x] Allow use of last upload for subsequent parameter changes/calculations by default. fb85cf479ba0c199aae08ef015139d484ff044ee
- [x] **Add POSCAR support** 041bead7e3cbba0ba7592b7038ac7a23d21798bb
- [x] Finish custom validator using `ase.io.read` 85201a5d7304765cada5f5cf224aeb823af59ee5
