### ISSUE TITLE
VXRD: Enhancements

### ISSUE THREAD

**Issue by sabaronett** [qzhu2017/XRD#21]
- [x] Move all web-app related files to top-level `flask/` directory.
- [x] JSmol
   - [x] Determine if install-able as separate dependency w/o including in source https://github.com/qzhu2017/XRD/issues/21#issuecomment-594730588
   - [x] Embed next to submission form (to the right) 9994626d4b41c8f4480f7b0de3f0dbda131a3af3
   - [x] Default "Unit cell" size: 1x1x1 https://github.com/qzhu2017/XRD/issues/21#issuecomment-594989085
   - [x] Set "Unit cell" list options: current good https://github.com/qzhu2017/XRD/issues/21#issuecomment-594989085
   - [x] Download as "json" needed? No https://github.com/qzhu2017/XRD/issues/21#issuecomment-594989085
   - [x] Remove "Download" 77d36e2cc25780271f8682a6b3905cb7fe9a85e7
- [x] Site footer (w/ copyright, year, authors, etc.) e2d87eb172f55d7f04e64677b925a882cf715924
- [x] "Source" link to GitHub repo 6917c8c096a32daa04ad66e3ee29805de84ffb8d
- [x] Make alerts [dismissible ](https://getbootstrap.com/docs/3.3/components/#alerts-dismissible) 8a82cbad6c5b44420c1752c37cbc96a995714f90
- [x] Red color palette (`custom.css`) c52a7944261db60b067755280458db4d4251f424
- [x] VXRD Logo: Bragg's law "V" f2a5467bfd10fd88b84f29883631328e65513b4f
- [x] Homepage w/ hero 5fe4b8e942605f44fcca2977fed0991c6cca342c
- [ ] Contact form
- [ ] [Progress bars](https://getbootstrap.com/docs/3.3/components/#progress)
- [ ] Implement "[background jobs](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxii-background-jobs)" for calculations

**Comment by sabaronett** [comment]
@qzhu2017, for JSmol, do we want to include the _unzipped_ `static/jsmol` in this repo or just `jsmol.zip` and instruct the end-user to unpack it themselves? Unpacking it makes it easier for anyone cloning the repo, but it will also commit almost 2,000 individual files and add another ~80 MBs.

Let me know what you prefer.

![image](https://user-images.githubusercontent.com/51060809/75908476-1050dd00-5dff-11ea-905a-5f77940446a5.png)

**Comment by qzhu2017** [comment]
@sabaronett  Let's just keep this file local and do not upload it to github repo

**Comment by sabaronett** [comment]
@qzhu2017 JSmol has been added in 9994626d4b41c8f4480f7b0de3f0dbda131a3af3. Per c01e932873e950281bccf42e26914bac3b956171, you'll need to unzip `jsmol.zip` in the right subfolder (where `jsmol.js` is).

After checking it out, what's your thoughts on the following open questions?
- Default "Unit cell" size? (currently 1x1x1)
- Set "Unit cell" list options? (see current dropdown)
- Is download as "json" needed? (see "xyz" under "Download" dropdown)
- How best to implement on "Comparison" page? Two JSmols? Only the first?

**Comment by qzhu2017** [comment]
> @qzhu2017 JSmol has been added in [9994626](https://github.com/qzhu2017/XRD/commit/9994626d4b41c8f4480f7b0de3f0dbda131a3af3). Per [c01e932](https://github.com/qzhu2017/XRD/commit/c01e932873e950281bccf42e26914bac3b956171), you'll need to unzip `jsmol.zip` in the right subfolder (where `jsmol.js` is).
> 
> After checking it out, what's your thoughts on the following open questions?
> 
> * Default "Unit cell" size? (currently 1x1x1)
Yes
> * Set "Unit cell" list options? (see current dropdown)
no need to change
> * Is download as "json" needed? (see "xyz" under "Download" dropdown)
I don't think we need this option
> * How best to implement on "Comparison" page? Two JSmols? Only the first?
Maybe two JSmols and arrange them vertically?
@sabaronett wow thanks. Are you coming to school tomorrow? or video meeting?

**Comment by sabaronett** [comment]
I'm coming to school tomorrow. I'll finish classes around 12:45 PM. Come to your office afterwards?

**Comment by sabaronett** [comment]
@qzhu2017, I'm coming to school tomorrow. I'll finish classes around 12:45 PM. Come to your office afterwards?

**Comment by qzhu2017** [comment]
@sabaronett sounds good. see u tomorrow
