### ISSUE TITLE
VXRD: Forms

### ISSUE THREAD

**Issue by sabaronett** [qzhu2017/XRD#22]
## Tasks
- [x] Turn on debug mode until app goes live 7163d67b80d299a99735daf976476096a0e61147
- [x] 5 to 180 for 2&theta; 9ef33aa727423934449d42c5e1db86874482210a
- [x] 0.1 to 5 min/max for wavelength 9ef33aa727423934449d42c5e1db86874482210a
- [x] Add `FloatField` for min2theta 7f4efc7012385a2f71ee4c12806db7432b4c8f5e
- [x] Add `FloatField` for profiling resolution _res_ (`default=0.01`) 24ff44535d75db111220825ba2f8d3f746990a6e
- [x] Add `SelectField` for profiling functions (`default=gaussian`) c5e8929ea061784473e3e42a1f51f6f81efa714b
- [x] [Link ](https://wiki.fysik.dtu.dk/ase/ase/io/io.html?highlight=formats#file-input-and-output)to ASE with acceptable upload formats 69ec34e3a1cb76341ed623c8cfd91f8f39347bfd
- [x] Flash "current file" message (normal alert) bea5aa2fc37be67fecff62da916307a4b72f52cd
- [x] Add `FloatField` for FWHM (`min=1e-3, max=1.0, default=0.02`) f279b04839bfc21cd9e4b8aa1de02983811a0e74
- [x] Add `FloatField`s for pseudo-Voigt (similar ranges) f279b04839bfc21cd9e4b8aa1de02983811a0e74
- [x] Implement multi-column form e40eb5250e220cf548ad83ee5a74eb0426f3a9bd
- [x] Dynamic sub-form for gaussian/lorentzian vs. pseudo_voigt params 7d966a2c5c366d22ffddff9401dbc6af063886f1
- [x] Finalize form layout ([sketch](https://github.com/qzhu2017/XRD/issues/22#issuecomment-588021386))
- [x] Put 2&theta; min/max fields on same line. 7d966a2c5c366d22ffddff9401dbc6af063886f1
- [x] Implement final form layout 7d966a2c5c366d22ffddff9401dbc6af063886f1
- [x] Fix pseudo-Voigt bug after submit c118a957a7edb70f5caabc874a9c483dfae32570
- [x] Add JSmol (moved to https://github.com/qzhu2017/XRD/issues/21#issue-557934598)
- [x] Set min/max for V (pseudo-Voigt) 28bba3671eeb6a73403a7cd1c3618e2acf11f940
- [x] Update titles to "Virtual X-ray Diffraction" (VXRD) 0c578a0938fd8ee20aa7de070e03ad43684515b0
- [x] Fix missing validation bug on profile param fields 7da42212b747ae229e34814f0b9735a64da1d31c
- [x] Investigate HTTP 500 on prod server for pseudo-Voigt profiling be0cbf99dc3e17fd7275a3ba4cfd1e9a006babc3

## Reference
- Profiling demo: https://github.com/qzhu2017/XRD/commit/671da9617f0503405abcd7ae8a59121215ea9a8f for reference in advanced form logic.

**Comment by sabaronett** [comment]
@qzhu2017 @sayred1 
I saw with 354fc09ef24980ed3b4dd74c118f16c29c6c3fa2 that the `get_profile()` function now takes a `res` argument, as in below:
```python
xrd.get_profile(res=0.01)
```

Before (when it used to be _N_), we wanted the default to be 10000. I'm assuming we now want this `res` argument to default to `0.01`? Also, what do you guys want to set for min/max values?

Thanks.

**Comment by qzhu2017** [comment]
@sabaronett 
let use 0.01 as the default, min=1e-3, max=1.

**Comment by qzhu2017** [comment]
@sabaronett 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/29445366/74598331-8fcf6580-5024-11ea-8728-25e910f7f145.png">
It is not urgent. But I think you need to rearrange the menus later. For instance, it is more convenient to put theta_max and min in the same line.

**Comment by qzhu2017** [comment]
@sabaronett 
I just tried to load NaCl.cif, but it output the following
<img width="670" alt="image" src="https://user-images.githubusercontent.com/29445366/74598360-0c624400-5025-11ea-8899-ddce2a99d78f.png">

**Comment by sabaronett** [comment]
@qzhu2017 
I'll add menu-rearrangements to the task list. I'm currently rendering a `quick_form` in the HTML template for simplicity (one line), but once we've finalized the form fields and functionality I can build the layout from scratch. We should meet to sketch and finalize the layout when we get there.

As for the error, can you try one of the working test files I've put in `/flask/instance/uploads` ([here](https://github.com/qzhu2017/XRD/tree/master/flask/instance/uploads))? I had to disable validation on the uploads so there are issues with some of the "bad" files in the `/dataset` directory.

Also, did you pull `/flask/.flaskenv` ([here](https://github.com/qzhu2017/XRD/blob/master/flask/.flaskenv))? You should only be getting that error page if debug-mode is off, and I've forced it on in that file when you run `flask run`.

**Comment by qzhu2017** [comment]
> @qzhu2017
> I'll add menu-rearrangements to the task list. I'm currently rendering a `quick_form` in the HTML template for simplicity (one line), but once we've finalized the form fields and functionality I can build the layout from scratch. We should meet to sketch and finalize the layout when we get there.
> 
> As for the error, can you try one of the working test files I've put in `/flask/instance/uploads` ([here](https://github.com/qzhu2017/XRD/tree/master/flask/instance/uploads))? I had to disable validation on the uploads so there are issues with some of the "bad" files in the `/dataset` directory.
> 
> Also, did you pull `/flask/.flaskenv` ([here](https://github.com/qzhu2017/XRD/blob/master/flask/.flaskenv))? You should only be getting that error page if debug-mode is off, and I've forced it on in that file when you run `flask run`.

Just realized that I used a new PC to run this app. After I installed the required python packages, the problem is gone!

**Comment by sabaronett** [comment]
Hahaha. Whew, you had me worried!

**Comment by sabaronett** [comment]
@qzhu2017 @sayred1 
Is there a min/max value you'd like to set for the pseudo-Voigt `V` parameter?

Also, here are the results of the different profiling methods implemented with their default parameter values:
### Gaussian
![gaussian](https://user-images.githubusercontent.com/51060809/74615697-e9dd3300-50d7-11ea-9c24-9415b830f18f.png)
### Lorentzian
![lorentzian](https://user-images.githubusercontent.com/51060809/74615701-ecd82380-50d7-11ea-8b2b-767ba32486a4.png)
### Pseudo-Voigt
![pseudo_voigt](https://user-images.githubusercontent.com/51060809/74615706-efd31400-50d7-11ea-98e1-b4767580cb22.png)

**Comment by sabaronett** [comment]
In order to get the profile-specific params working, I had to add arguments to the following lines:
https://github.com/qzhu2017/XRD/blob/58355bde56655843c936711da8bf4bb0007fe563/pyxtal_xrd/XRD.py#L51-L52

You'll have to rerun `python setup.py install` after you pull 58355bde56655843c936711da8bf4bb0007fe563, otherwise `flask/app/routes.py` will encounter an error when you try to submit.

Seems to be working. Here's an example NaCl lorentzian profile with FWHM=0.5:
![fwhm_0 5](https://user-images.githubusercontent.com/51060809/74616831-f44efb00-50de-11ea-8b1d-0054e3bd520c.png)

**Comment by qzhu2017** [comment]
@sabaronett @sayred1 
Are you guying coming to school tomorrow?

Can we have a meeting at my office regarding the following items

- [ ] Set min/max for V (pseudo-Voigt)
- [ ] Finalize form layout (sketch)
   - [ ] Put 2&theta; min/max fields on same line.
- [ ] Dynamic sub-form for gaussian/lorentzian vs. pseudo_voigt params
- [ ] Implement final form layout

I want to 
- finalize the sketch of layout
- clarify the profile function applied to PXRD computation.

**Comment by sayred1** [comment]
@qzhu2017 @sabaronett, I will be free after 12.

**Comment by sabaronett** [comment]
@qzhu2017 @sayred1 I finish class at 12:45 PM, so I can meet at your office by 1:00 PM.

**Comment by sabaronett** [comment]
Final layout sketch from today's meeting.

![layout](https://user-images.githubusercontent.com/51060809/74800205-990c3c80-5287-11ea-9f6e-085e43b99476.jpg)

**Comment by qzhu2017** [comment]
@sabaronett What is the progress?

> Final layout sketch from today's meeting.
> 
> ![layout](https://user-images.githubusercontent.com/51060809/74800205-990c3c80-5287-11ea-9f6e-085e43b99476.jpg)

@s

**Comment by sabaronett** [comment]
@qzhu2017, sorry, I've been busy with my research so no progress, but I can spend some time this weekend or maybe sooner. I'll let you know.

**Comment by sabaronett** [comment]
@qzhu2017, aside from adding JSmol, the layout with the dynamic JS toggling of the profiling sub-forms is done in 7d966a2c5c366d22ffddff9401dbc6af063886f1. However, there's kind of a bug where the sub-form defaults to FWHM after pseudo-Voight is submitted. It only re-updates with a profile "'double" change. I've added this bug to my task list.

**Comment by qzhu2017** [comment]
@sabaronett 
I see. After you fix this, let me know if you need any help on JSmol. I may be able to help on that.

**Comment by sabaronett** [comment]
@qzhu2017 Fixed it! c118a957a7edb70f5caabc874a9c483dfae32570 😀 And I learned something new in the process: _jQuery_. I had seen the name before, but never knew what it was, as it wasn't developed until _after_ I learned web development back in high school.

I don't have class tomorrow (Wednesday), so I should be able to spend a lot of time on this project and hopefully get the JSmol working and more.

By the way, is there a preferred min/max value for V (pseudo-Voigt) parameter? It's currently defaulted to **-0.00167383**

**Comment by qzhu2017** [comment]
@sabaronett Thanks for fixing the bug. For V parameter, let's just leave as it is. I don't think there will be a need to change this parameter.

**Comment by sabaronett** [comment]
@qzhu2017, I meant there's currently no validation protection for that field, so the user can enter any nonsense float and potentially cause an error. If it should remain fixed then maybe we don't offer it as a field. Otherwise, make the validation range something like  [-0.002, -0.001 ]?

Let me know what you think. Thanks.

**Comment by qzhu2017** [comment]
@sabaronett Yes, you can put some range between [-0.002, -0.001]

**Comment by sabaronett** [comment]
Task list as of 3/16/2020 complete.

Closing issue.
