### ISSUE TITLE
VXRD: Experimental Data

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/XRD#28]
## Tasks
- [ ] Create new route for experimental comparison.
- [ ] Copy new HTML template from existing comp.
- [ ] Add new `FileField` to `forms.py` w/ diff. description (e.g., "Experimental data")
- [ ] Update `upload` field (`forms.py`) description to "Structure File"
- [ ] Update `base.html` w/ navbar link

@sabaronett 
This webpage will be similar to #27 except that it does not takes the 2nd structure as the reference. It will take the experimental PXRD pattern with 2D array (2theta, peaks)

I will upload some experimental data file and script later.

**Comment by sabaronett** [comment]
Cool, sounds good. Let me know.
