### ISSUE TITLE
VXRD: Self-Gen. Structs

### ISSUE THREAD

**Issue by sabaronett** [qzhu2017/XRD#29]
## Tasks
- [ ] Dynamic Energy vs. Similarity scatter plot (JS)
- [ ] E vs. S points show corresponding plotly (on-click)
- [ ] Historical jobs queued/listed w/ progress and cancelation.

**Comment by sabaronett** [comment]
Sketch from today's meeting.
![IMG_20200218_142224](https://user-images.githubusercontent.com/51060809/74800450-5a2ab680-5288-11ea-8c8b-8f7bd5fdf850.jpg)
